hw4 : HashTable.cpp LinkedList.cpp List.cpp Queue.cpp Stack.cpp Word.cpp WordNetwork.cpp main.cpp
	g++  HashTable.cpp LinkedList.cpp List.cpp Queue.cpp Stack.cpp Word.cpp WordNetwork.cpp main.cpp -o hw4
